###############################################################################
## dev 开发环境
###############################################################################
## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://192.168.171.127:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: b6xi17k4hWT5+/guISAfGhwaIgIUb/YEPHe8Rr8hsHWECVpMo74kfUCD/07ZpQDYVQEiZmhVqzgWTHdxLl+eLg==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIJMnP1KNZjrn+I86N9HgYFNqSsXVDM+Z2SIKvAENMCmr6b9Cf914AGadatlo719T0xV8sS9z93vq22n5zZ6wPUCAwEAAQ==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
###############################################################################
## redis配置
  redis:
    host: 192.168.171.127
    port: 6379
    password: redis
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
###############################################################################
## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml
###############################################################################
## swagger配置
swagger:
  enable: true
###############################################################################
